config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

  validates :title, :author, :content, :status, :published_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      redirect_to @post, alert: 'Error creating comment.'
    end
  end


  def destroy
    # @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    ap @comment.id
    @comment.destroy

   redirect_to post_path(@post), notice: 'Comment was successfully destroyed.'
  end

  private


  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.where(status: 'published').paginate(page: params[:page], per_page: 8)
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :author, :content, :status, :published_date, :image, :video)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "devise"

  # If you have any custom logic to add to the controller, you can add it here.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar">
    <div class="navbar-content">
      <div class="navbar-links">
        <%= link_to 'Home', root_path %> |
        <% if user_signed_in? %>
          <%= link_to 'New Post', new_post_path %> |
        <% end %>
        <% if user_signed_in? %>
          <%= form_for :user, url: destroy_user_session_path, method: :delete, html: { class: "logout-form" } do %>
            <%= submit_tag "Logout", class: "logout-button" %>
          <% end %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path %> |
          <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </div>
    </div>
  </nav>

  <%= yield %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp - Authentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'devise', media: 'all' %> <!-- Custom stylesheet for Devise -->
  </head>

  <body>
    <div class="auth-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, html: { multipart: true, class: "form-horizontal" }) do |form| %>
  <div class="form-group">
    <%= form.label :title, class: "control-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :author, class: "control-label" %>
    <%= form.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content, class: "control-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :status, class: "control-label" %>
    <%= form.select :status, options_for_select([['Draft', 'draft'], ['Published', 'published']]), {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :published_date, class: "control-label" %>
    <%= form.datetime_select :published_date, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :image, class: "control-label" %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= form.label :video, class: "control-label" %>
    <%= form.file_field :video, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h3>Edit Post</h3>
        </div>
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <div class="container mt-5">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card h-100 shadow-sm">
            <% if post.image.present? %>
              <div class="card-img-container">
                <%= image_tag post.image.url, class: "fixed-size-image" %>
              </div>
            <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= link_to post.title, post %></h5>
              <p class="card-text"><%= truncate(post.content, length: 100) %></p>
              <p class="text-muted">By <%= post.author %></p>
              <% if post.video.present? %>
                <video width="100%" controls class="mt-2">
                  <source src="<%= post.video.url %>" type="video/mp4">
                  Your browser does not support the video tag.
                </video>
              <% end %>
              <% if user_signed_in? && post.user == current_user %>
                <div class="mt-auto">
                  <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary mr-2' %>
                  <%= button_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="pagination justify-content-center mt-4">
      <%= will_paginate @posts, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>
  </div>
<% else %>
  <div class="container mt-5">
    <div class="alert alert-warning" role="alert">
      <h4 class="alert-heading">No Posts Available</h4>
      <p>It looks like there are no posts yet. Why not <%= link_to 'create one', new_post_path %>?</p>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h3>New Post</h3>
        </div>
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mb-4">
        <% if @post.image.present? %>
          <%= image_tag @post.image.url, class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <h1 class="card-title"><%= @post.title %></h1>
          <p class="card-text"><%= @post.content %></p>
          <p class="text-muted">By <%= @post.author %></p>
          <% if @post.video.present? %>
            <video width="100%" controls class="mt-2">
              <source src="<%= @post.video.url %>" type="video/mp4">
              Your browser does not support the video tag.
            </video>
          <% end %>
          <% if user_signed_in? && @post.user == current_user %>
            <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary mr-2' %>
            <%= button_to 'Delete', post_path(@post), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>

      <div class="card mb-4">
        <div class="card-body">
          <% @post.comments.each do |comment| %>
            <div class="comment mb-3">
              <p><strong><%= comment.user.email %>:</strong> <%= comment.body %></p>
              <% if user_signed_in? && @post.user == current_user %>
                 <%= form_with(url: post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' }) do |form| %>
                  <%= form.submit 'Delete Comment', class: 'btn btn-danger btn-sm' %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="card mb-4">
          <div class="card-body">
            <p><strong><%= current_user.email %>:</strong></p>
            <%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>
              <div class="form-group">
                <%= form.label :body, "Comment", class: "control-label" %>
                <%= form.text_area :body, class: "form-control", rows: 3 %>
              </div>
              <%= form.submit 'Post Comment', class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <p>You must be logged in to leave a comment.</p>
      <% end %>
    </div>
  </div>
</div>